-- create db: core tables, enums, indexes, and rls policies
-- notes: run in order; tables first, policies after

-- region: tables
-- enums for recipe lifecycle and user actions
create type public.recipe_status_enum as enum ('draft', 'saved', 'rejected', 'deleted');
create type public.recipe_action_enum as enum ('accepted', 'edited', 'rejected');

-- brew methods catalog (publicly readable)
create table public.brew_methods (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  created_at timestamptz not null default now()
);

comment on table public.brew_methods is 'catalog of supported brew methods';
comment on column public.brew_methods.slug is 'url-safe identifier for brew method';

-- generation requests issued by users
create table public.generation_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  brew_method_id uuid not null references public.brew_methods (id) on delete restrict,
  coffee_amount numeric(6,1) not null check (coffee_amount >= 0),
  can_adjust_temperature boolean not null,
  user_comment text null,
  created_at timestamptz not null default now()
);

comment on table public.generation_requests is 'raw user inputs used to generate recipes';

-- recipes generated by ai or manually created by users
create table public.recipes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  generation_request_id uuid null references public.generation_requests (id) on delete set null,
  brew_method_id uuid not null references public.brew_methods (id) on delete restrict,
  coffee_amount numeric(6,1) not null check (coffee_amount >= 0),
  water_amount numeric(6,1) not null check (water_amount >= 0),
  ratio_coffee int not null check (ratio_coffee >= 1),
  ratio_water int not null check (ratio_water >= 1),
  temperature int not null check (temperature between 0 and 100),
  assistant_tip text null,
  status public.recipe_status_enum not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.recipes is 'generated and manually created recipes';

-- action logs for accepted/edited/rejected recipes
create table public.recipe_action_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  recipe_id uuid not null references public.recipes (id) on delete cascade,
  generation_request_id uuid null references public.generation_requests (id) on delete set null,
  action public.recipe_action_enum not null,
  created_at timestamptz not null default now()
);

comment on table public.recipe_action_logs is 'audit trail of user decisions on recipes';

-- indexes for query performance based on db plan
create index generation_requests_user_created_at_idx
  on public.generation_requests (user_id, created_at);

create index generation_requests_brew_method_id_idx
  on public.generation_requests (brew_method_id);

create index recipes_user_created_at_idx
  on public.recipes (user_id, created_at);

create index recipes_generation_request_id_idx
  on public.recipes (generation_request_id);

create index recipes_brew_similarity_idx
  on public.recipes (brew_method_id, coffee_amount, ratio_coffee, ratio_water, temperature);

create index recipe_action_logs_user_created_at_idx
  on public.recipe_action_logs (user_id, created_at);

create index recipe_action_logs_recipe_created_at_idx
  on public.recipe_action_logs (recipe_id, created_at);

create index recipe_action_logs_action_idx
  on public.recipe_action_logs (action);
-- endregion: tables

-- region: policies
-- enable rls even for public tables (required by project standards)
alter table public.brew_methods enable row level security;
alter table public.generation_requests enable row level security;
alter table public.recipes enable row level security;
alter table public.recipe_action_logs enable row level security;

-- public read access for brew methods
create policy "brew_methods_select_anon"
  on public.brew_methods
  for select
  to anon
  using (true);

create policy "brew_methods_select_authenticated"
  on public.brew_methods
  for select
  to authenticated
  using (true);

-- user-owned access policies for generation requests
create policy "generation_requests_select_anon"
  on public.generation_requests
  for select
  to anon
  using (user_id = auth.uid());

create policy "generation_requests_select_authenticated"
  on public.generation_requests
  for select
  to authenticated
  using (user_id = auth.uid());

create policy "generation_requests_insert_anon"
  on public.generation_requests
  for insert
  to anon
  with check (user_id = auth.uid());

create policy "generation_requests_insert_authenticated"
  on public.generation_requests
  for insert
  to authenticated
  with check (user_id = auth.uid());

create policy "generation_requests_update_anon"
  on public.generation_requests
  for update
  to anon
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy "generation_requests_update_authenticated"
  on public.generation_requests
  for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy "generation_requests_delete_anon"
  on public.generation_requests
  for delete
  to anon
  using (user_id = auth.uid());

create policy "generation_requests_delete_authenticated"
  on public.generation_requests
  for delete
  to authenticated
  using (user_id = auth.uid());

-- user-owned access policies for recipes
create policy "recipes_select_anon"
  on public.recipes
  for select
  to anon
  using (user_id = auth.uid());

create policy "recipes_select_authenticated"
  on public.recipes
  for select
  to authenticated
  using (user_id = auth.uid());

create policy "recipes_insert_anon"
  on public.recipes
  for insert
  to anon
  with check (user_id = auth.uid());

create policy "recipes_insert_authenticated"
  on public.recipes
  for insert
  to authenticated
  with check (user_id = auth.uid());

create policy "recipes_update_anon"
  on public.recipes
  for update
  to anon
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy "recipes_update_authenticated"
  on public.recipes
  for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy "recipes_delete_anon"
  on public.recipes
  for delete
  to anon
  using (user_id = auth.uid());

create policy "recipes_delete_authenticated"
  on public.recipes
  for delete
  to authenticated
  using (user_id = auth.uid());

-- user-owned access policies for recipe action logs
create policy "recipe_action_logs_select_anon"
  on public.recipe_action_logs
  for select
  to anon
  using (user_id = auth.uid());

create policy "recipe_action_logs_select_authenticated"
  on public.recipe_action_logs
  for select
  to authenticated
  using (user_id = auth.uid());

create policy "recipe_action_logs_insert_anon"
  on public.recipe_action_logs
  for insert
  to anon
  with check (user_id = auth.uid());

create policy "recipe_action_logs_insert_authenticated"
  on public.recipe_action_logs
  for insert
  to authenticated
  with check (user_id = auth.uid());

create policy "recipe_action_logs_update_anon"
  on public.recipe_action_logs
  for update
  to anon
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy "recipe_action_logs_update_authenticated"
  on public.recipe_action_logs
  for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy "recipe_action_logs_delete_anon"
  on public.recipe_action_logs
  for delete
  to anon
  using (user_id = auth.uid());

create policy "recipe_action_logs_delete_authenticated"
  on public.recipe_action_logs
  for delete
  to authenticated
  using (user_id = auth.uid());
-- endregion: policies
